const DEALERSHIP_WORKING_HOURS = {
    START_TIME: '09:00 AM',
    END_TIME: '05:00 PM'
};
const BOOKING_DURATION_IN_HOURS = 2;
const BOOKING_CAPACITY_KEY = 'setting:booking-capacity';
const DEFAULT_BOOKING_CAPACITY = 2;

export {
    DEALERSHIP_WORKING_HOURS,
    BOOKING_DURATION_IN_HOURS,
    BOOKING_CAPACITY_KEY,
    DEFAULT_BOOKING_CAPACITY
};

